server:
  port: 9002

spring:
  application:
    name: user-service
    mongodb:
      uri: mongodb://localhost:27017/microservices1-db
  #  datasource:
  #    username: root
  #    password: password
  #    url: jdbc:mysql://localhost:3306/testdb
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  data:

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400